// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2in2Wg6o9vCSjWr1-oJOqD4MetF4b61o',
    appId: '1:601132843655:web:3cae2f6ca3418b49e96e22',
    messagingSenderId: '601132843655',
    projectId: 'toptancistoktakipapp',
    authDomain: 'toptancistoktakipapp.firebaseapp.com',
    storageBucket: 'toptancistoktakipapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7eC7CniLR8awZlC6YhMEettZlTIAaZBM',
    appId: '1:601132843655:android:ba909df221e50446e96e22',
    messagingSenderId: '601132843655',
    projectId: 'toptancistoktakipapp',
    storageBucket: 'toptancistoktakipapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8D9HIDxzxxj55sotT62g1KMuubDbpTc',
    appId: '1:601132843655:ios:093512774d1c87d8e96e22',
    messagingSenderId: '601132843655',
    projectId: 'toptancistoktakipapp',
    storageBucket: 'toptancistoktakipapp.appspot.com',
    iosBundleId: 'com.example.toptanciStokTakipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8D9HIDxzxxj55sotT62g1KMuubDbpTc',
    appId: '1:601132843655:ios:093512774d1c87d8e96e22',
    messagingSenderId: '601132843655',
    projectId: 'toptancistoktakipapp',
    storageBucket: 'toptancistoktakipapp.appspot.com',
    iosBundleId: 'com.example.toptanciStokTakipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2in2Wg6o9vCSjWr1-oJOqD4MetF4b61o',
    appId: '1:601132843655:web:701b56b19977c432e96e22',
    messagingSenderId: '601132843655',
    projectId: 'toptancistoktakipapp',
    authDomain: 'toptancistoktakipapp.firebaseapp.com',
    storageBucket: 'toptancistoktakipapp.appspot.com',
  );
}
